"""empty message

Revision ID: 0b621f61b69c
Revises: 3488bee76e12
Create Date: 2020-07-09 23:22:48.526434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b621f61b69c'
down_revision = '3488bee76e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('likes', sa.Integer(), nullable=False))
    op.drop_column('product', 'likes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'likes')
    # ### end Alembic commands ###
