"""empty message

Revision ID: 1fbad948af62
Revises: 6b610124db56
Create Date: 2020-11-27 19:11:47.690358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbad948af62'
down_revision = '6b610124db56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_category')
    op.drop_column('store', 'phone_number')
    op.drop_column('store', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('store', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('store_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='store_category_pkey')
    )
    # ### end Alembic commands ###
