"""Reset likes relationships

Revision ID: 283f032fa083
Revises: 7f22e1708da8
Create Date: 2020-07-10 01:32:01.065166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283f032fa083'
down_revision = '7f22e1708da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
