"""empty message

Revision ID: 55df1d10f636
Revises: b84d314aab62
Create Date: 2020-11-27 20:26:02.195951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55df1d10f636'
down_revision = 'b84d314aab62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('store_category_id_fkey', 'store', type_='foreignkey')
    op.create_foreign_key(None, 'store', 'store_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.create_foreign_key('store_category_id_fkey', 'store', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
