"""empty message

Revision ID: 7f22e1708da8
Revises: 0b621f61b69c
Create Date: 2020-07-09 23:30:51.095628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f22e1708da8'
down_revision = '0b621f61b69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
