"""Added store departments

Revision ID: 9c884c2caea0
Revises: 55df1d10f636
Create Date: 2020-11-27 21:08:51.053494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c884c2caea0'
down_revision = '55df1d10f636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('store', sa.Column('departament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'store', 'department', ['departament_id'], ['id'])
    op.drop_column('store', 'departamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('departamento', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_column('store', 'departament_id')
    op.drop_table('department')
    # ### end Alembic commands ###
