"""Added store categories

Revision ID: b84d314aab62
Revises: 0142a970f80a
Create Date: 2020-11-27 20:17:40.280135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84d314aab62'
down_revision = '0142a970f80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('store', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('store', sa.Column('email', sa.String(), nullable=True))
    op.add_column('store', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_foreign_key(None, 'store', 'category', ['category_id'], ['id'])
    op.drop_column('store', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_column('store', 'phone_number')
    op.drop_column('store', 'email')
    op.drop_column('store', 'category_id')
    op.drop_table('store_category')
    # ### end Alembic commands ###
