"""Test Shopping cart 4.0

Revision ID: c34c11faafd4
Revises: c724cf3d3229
Create Date: 2020-07-12 15:12:43.253960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34c11faafd4'
down_revision = 'c724cf3d3229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item', 'id')
    # ### end Alembic commands ###
